### PR TITLE
Merge lists

### PR DESCRIPTION
**Pull request by Freekers**
I added three domains, please review and merge to keep your list up to date. Thank you.

### CODE REVIEW

**Comment by anudeepND** [comment]
@Freekers are these domains blocked in any blocklists?

**Comment by Freekers** [comment]
@anudeepND  Yes, all three are blocked in 'raw.githubusercontent.com.domains'. To be honest, I don't know which one it is exactly, but it should be one of these: https://pastebin.com/dEahSm4Z

**Comment by anudeepND** [comment]
The default list should not contain any bad domains so...

**Comment by anudeepND** [comment]
@Freekers I have added few domains to repo, you can close this PR,.

**Comment by Freekers** [comment]
Ah sorry, my bad. I will remove them.

**Pull request closed without merging**
