### PR TITLE
Add petri.com

### PR DESCRIPTION
**Pull request by mc9662**
Match found in https://v.firebog.net/hosts/Airelle-trc.txt:
www.petri.com

Petri.com is a known IT knowledgebase

### CODE REVIEW

**Comment by pahakalle** [comment]
What page gets affected by this domain being blocked and how does it affect the page?

**Comment by mc9662** [comment]
The whole website www.petri.com is blocked.  It's a tech resource page convering Micorsoft tech

**Comment by anudeepND** [comment]
@mc9662 Thanks for reporting. I have sent an email to the maintainer about this issue. I will add it to the list if he refuses to remove the domain from his list.

**Comment by anudeepND** [comment]
@mc9662 He replied via email that he will remove the domain in the next update.

**Pull request closed without merging**
