### PR TITLE
Update optional-list.txt

### PR DESCRIPTION
**Pull request by alexruf**
- 4players not loading
- Google Docs not loading
- YouTube on mobile devices
- Google Translate not loading

### CODE REVIEW

**Comment by anudeepND** [comment]
@alexruf Thanks for the PR, but I don't see these domains on default blocklists. Can you mention the host files in which these domains are blocked?

**Comment by alexruf** [comment]
I have to apologize for the PR. Seems like you're right and the domains are not blocked by the default filter lists, but from an additional filter list which was added.
Sorry!

**Comment by kyle95wm** [comment]
Can you please share that list with us anyways?

**Comment by alexruf** [comment]
Sure. Before I discovered Pi-hole, I was using AdGuard on my desktop & mobiles. Since I am located in Germany the default Pi-hole lists don't work well for me.
So I just added the [AdGuard filter lists](https://kb.adguard.com/en/general/adguard-ad-filters).
Especially the following once:
- [English filter](https://kb.adguard.com/en/general/adguard-ad-filters#english-filter)
- [Spyware filter](https://kb.adguard.com/en/general/adguard-ad-filters#spyware-filter)
- [German filter](https://kb.adguard.com/en/general/adguard-ad-filters#german-filter)
- [Mobile ads filter](https://filters.adtidy.org/extension/chromium/filters/11.txt)

**Comment by PascalMinder** [comment]
Is it possible to import those lists directly into pihole?

**Comment by anudeepND** [comment]
@alexruf Thanks for the information. I will check these domains with [Wally3k's](https://firebog.net) lists, if I found these domains in those host files I will add them to whitelist

**Comment by alexruf** [comment]
> @PascalMinder No you cannot use these filters with Pi-Hole since it's not in host file format.

Thanks for the hint, didn't recognize that they format of those lists is different. Well, I was able to import them anyway and it didn't complain about the format. They seem to partially work anyway since most of the ads are blocked for me now.

**Comment by anudeepND** [comment]
@alexruf These domains are not blocked in any of the block lists. However I will keep an eye on these domains.

**Pull request closed without merging**
