### PR TITLE
Update whitelist.sh

### PR DESCRIPTION
**Pull request by ChrisPhillips-cminion**
Removed the need for gawk, removed unused waits and reduced some sleeps. 

It also backs up the whitelist prior to the removal of duplications

### CODE REVIEW

**Comment by anudeepND** [comment]
@ChrisPhillips-cminion This PR fixes gawk issue on Centos 7 right? Take a look https://github.com/anudeepND/whitelist/issues/66

**Comment by ChrisPhillips-cminion** [comment]
I imagine so, as it removes hte need for gawk. It works on fedora and ubuntu but not tried elsewhere.

**Comment by ChrisPhillips-cminion** [comment]
gawk is replaced by `sort` and `uniq` which are unix stable packages

**Comment by anudeepND** [comment]
@ChrisPhillips-cminion that's great then. Merging...

**Pull request merged**
