### PR TITLE
remove error prone total_changes function introduced in #158

### PR DESCRIPTION
**Pull request by mwoolweaver**
also fix merge issue of #163

### CODE REVIEW

**Comment by anudeepND** [comment]
@mwoolweaver Thank you for your contribution. Merging.

**Comment by anudeepND** [comment]
@mwoolweaver The `whitelist.py` outputs the number of domains added as 188 domains and does not show the actual number. 

Steps to reproduce:

1. clone the latest version 
2. delete some of the entries in your whitelist
3. run the script
4. it will always show 188 domains added to the whitelist

**Comment by mwoolweaver** [comment]
is that because the script is pulling from github and not the database that's cloned with the script?

https://github.com/anudeepND/whitelist/blob/master/scripts/whitelist.py#L75

**Comment by mwoolweaver** [comment]
the way to actually test this is to add a domain that is known to be whitelisted by the script to you whitelist before you run the script (DO NOT LEAVE A COMMENT) and it will not add that domain and will show a different number.

image

**Comment by mwoolweaver** [comment]
Or @anudeepND you’re talking about if a user is updating the list? I will agree in that area cause of the way it verifies domains being adding is just checking for their presence in the database which would have that caveat.

**Comment by mwoolweaver** [comment]
I am currently investigating checking `date_added` in pi-hole's database for the current date.

**Comment by mwoolweaver** [comment]
@anudeepND please see #166 for a fix I hope

**Pull request merged**
