### PR TITLE
add logic 

### PR DESCRIPTION
**Pull request by mwoolweaver**
- checks how many domains from this script are in database.
 - checks if any user added domains are in the script 
 - will skip \_if\_ all domains from script are present in Database && have a comment 

caveat
 - I have not figured out how to domains that do not have a comment. (blank in web GUI)

### CODE REVIEW

**Comment by mwoolweaver** [comment]
> Just in terms of Just in terms of constructive criticism,

I'm always open to constructive criticism and you bring up some good points

> are you currently determining whether the numbers / domains match up by counting the lines of the remote SQL file against number of rows in the DB?

yes that's [how](https://github.com/anudeepND/whitelist/commit/92e2e696a49801b969e73d39f7364c83a9cd43ac#diff-ae558a92912d7c9374a906e64b4b158eR139) it was done before me so I just continued the trend. I'm sure it could be made a bit better.

>  but what if the remote file swaps out test.com for test2.com? Your numbers would still match up but your results wouldn't necessarily mirror the remote list. And during the update how are you currently accommodating for domains that may have been added in the last run, where the domain may have since been removed from the remote whitelist?

I currently do [this](https://github.com/anudeepND/whitelist/pull/170/files#diff-ae558a92912d7c9374a906e64b4b158eR182) to check if a domain to be added is in the database but not added by the script. I'm sure this could be modified for further sanity check of domains in other ways, \_but\_ w/o keeping a previous version of the file locally or on GitHub? I'm not real sure how to track changes between runs of the script? 

AFAIK this is a current caveat as well as the script attempts to [`INSERT OR IGNORE` ALL](https://github.com/anudeepND/whitelist/blob/master/scripts/whitelist.py#L167) domains present in the script. I'm sure this could be addressed by not using a script to insert them all and \_instead\_ only insert those that need to be inserted.

**Comment by anudeepND** [comment]
@mwoolweaver @mmotti  I'm still a learner so my python code isn't great :smile:

**Comment by mwoolweaver** [comment]
@anudeepND me too! With your 2.0 update you triggered my want to learn when I saw python and sql I couldn't resist giving it a go. Hopefully you don't mind the P/R's and hopefully I leave enough comments in my code that everyone can understand what is happening.

Also don't rush to merge this as I'd say it's still a WIP for it to accomplish it's title but I'm working towards the goal now. Almost have all logic worked out 

### logic
 * check for user added domains in script
 * check for domains added by script that are not in updated script (optionally remove them)
 * check updated script against database and "only add those that aren't present or that the user has added already"

let me know if I missed a case

**Comment by anudeepND** [comment]
@mwoolweaver so far everything looks good to me. I will keep this PR open for a while if someone wants to add anything

**Comment by mwoolweaver** [comment]
So I think I have all the logic worked out. 

Here is my initial attempt at making it work https://github.com/mwoolweaver/whitelist/commit/20beea94455e85d12841822d585e01aaf064198f (it will say it is adding/deleting but it's not I want to make sure the logic works first)

worth noting is I haven't tried running this yet but my visual inspection thinks it should work, that could be wrong tho. . .

Please also note the changes I made to domains.sql --> https://github.com/mwoolweaver/whitelist/commit/1aef09682bda96746ebb6c8bc62e0a60995d4b3c so I could hopefully handle single `INSERT` statements dynamically

**Comment by mwoolweaver** [comment]
closed in favor of  #172

**Pull request closed without merging**
