### PR TITLE
Added domain cdn.ravenjs.com

### PR DESCRIPTION
**Pull request by pahakalle**
Fixes issue #64

### CODE REVIEW

**Comment by anudeepND** [comment]
@pahakalle Adding this domain to default list is not a good idea.
Please take a look at https://github.com/StevenBlack/hosts/issues/705 and https://github.com/lightswitch05/hosts/commit/6a256c58cc46b43e5961373c3e5640743c178932#commitcomment-29581997

**Comment by anudeepND** [comment]
@lightswitch05 What do you think?

**Comment by lightswitch05** [comment]
> Airthings Dashboard for the Wave Radon detector appears to require `cdn.ravenjs.com`

Any website that seems to require `cdn.ravenjs.com` is only failing because of poor error handling. `cdn.ravenjs.com` does not contain any functional code that a website might depend on to provide a service. If you want to whitelist it then that is your decision. It is very similar to `newrelic.com` - in fact the CEO said in an interview that his goal is to replace newrelic. I see newrelic is in your blacklist, so by that logic `cdn.ravenjs.com` should also be blocked. There are a couple statements in their [Privacy Policy](https://sentry.io/privacy) that I don't particularly care for:

> We may use your data to improve our advertising campaigns, primarily in an effort to prevent targeting of impressions via third-party channels when they are not relevant to you.

> We may use and share aggregated non-personal information with third parties for marketing, advertising, and analytics purposes.

**Comment by pahakalle** [comment]
Not much to add there closing this for not at least.

**Pull request closed without merging**
