### PR TITLE
Optional-list commands in README

### PR DESCRIPTION
**Pull request by eugf**
Added the commands for the optional-list

### CODE REVIEW

**Comment by anudeepND** [comment]
@eugf I don't think that we should add these commands because users do not use every services in those file, they can select the domains depending on the service they use.
I would like to hear your opinion before closing.

**Comment by eugf** [comment]
Hmm, I don't use these services enough to give a very informed opinion. As a general guess, I would expect the GeForce Nvidia, ESPN, Roku, and DirectTV to be the more frequently used ones. Ideally, if someone who has these services could test it out and see the effect of whitelisting and blacklisting them could chime that would probably be the best way to determine usefulness.

My use case is actually on a different host based blocker (not Pihole) that only takes entire lists and I just needed it for the Jackbox one. It's not a particularly compelling reason to add the command, it's more just for convenience. I will defer to your position on this.

**Comment by anudeepND** [comment]
I think it's better to leave this file as it is, and what about adding some domains from this file to `whitelist.txt`?

**Comment by eugf** [comment]
That can work, but it would be best if we had some testers try out those domains and see the impact. If the services are functional while these domains are blocked, it's probably best to leave on the "optional" list.

**Comment by anudeepND** [comment]
I will look into it :)  @eugf

**Pull request closed without merging**
